name: Wildberries Feedback Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Каждые 30 минут
  push:
    branches: [ main ]
  workflow_dispatch:  # Разрешить ручной запуск

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Wildberries Bot
      env:
        WB_API_KEY: ${{ secrets.WB_API_KEY }}
        SUPPLIER_ID: ${{ secrets.SUPPLIER_ID }}
        AI_PROVIDER: ${{ secrets.AI_PROVIDER || 'free' }}
        YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
        YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CHECK_INTERVAL: 30
        TEST_MODE: false
      run: |
        echo "🚀 Запуск Wildberries Bot..."
        python main.py
        echo "✅ Бот завершил работу"
